// Read-only Figma Plugin API export. Set PAGE_ID and OFFSET for each request.
// Return chunks in offset order; decode with decode-export.py. Never edits nodes.
const PAGE_ID = '13:177';
const OFFSET = 0;
const p=await figma.getNodeByIdAsync(PAGE_ID);await figma.setCurrentPageAsync(p);
const keys=['type','width','height','relativeTransform','visible','opacity','fills','strokes','strokeWeight','strokeAlign','strokeCap','strokeJoin','dashPattern','cornerRadius','topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius','clipsContent','effects','boundVariables','layoutMode','itemSpacing','paddingLeft','paddingRight','paddingTop','paddingBottom','primaryAxisAlignItems','counterAxisAlignItems','layoutSizingHorizontal','layoutSizingVertical','blendMode'];
const nodes=[],memo=new Map();function node(n,root=false){const out={};for(const k of keys){if(k in n&&typeof n[k]!=='symbol')out[k]=n[k];}if(root){out.relativeTransform=[[1,0,0],[0,1,0]];}if(n.type==='TEXT'){for(const k of ['characters','fontName','fontSize','fontWeight','lineHeight','letterSpacing','textAlignHorizontal','textAlignVertical','textDecoration','textCase','paragraphSpacing'])if(typeof n[k]!=='symbol')out[k]=n[k];out.segments=n.getStyledTextSegments(['fontName','fontSize','fontWeight','fills','lineHeight','letterSpacing','textDecoration']);}if(n.type==='VECTOR'){out.vectorPaths=n.vectorPaths;}if(n.type==='ELLIPSE')out.arcData=n.arcData;if('children'in n)out.children=n.children.map(c=>node(c));const key=JSON.stringify(out);if(memo.has(key))return memo.get(key);const idx=nodes.length;nodes.push(out);memo.set(key,idx);return idx;}
const sets=p.findAllWithCriteria({types:['COMPONENT_SET']});
const data={page:p.name,id:p.id,sets:sets.map(s=>({id:s.id,name:s.name,variants:s.children.map(n=>({id:n.id,properties:n.variantProperties,root:node(n,true)}))})),single:p.findAllWithCriteria({types:['COMPONENT']}).filter(n=>n.parent.type!=='COMPONENT_SET').map(n=>({id:n.id,name:n.name,root:node(n,true)})),nodes};
const raw=unescape(encodeURIComponent(JSON.stringify(data)));
const dict=new Map();let next=256,w='',codes=[];for(const c of raw){const wc=w+c;if(wc.length===1||dict.has(wc)){w=wc;}else{codes.push(w.length===1?w.charCodeAt(0):dict.get(w));if(next<65535)dict.set(wc,next++);w=c;}}if(w)codes.push(w.length===1?w.charCodeAt(0):dict.get(w));
const bytes=new Uint8Array(codes.length*2);codes.forEach((c,i)=>{bytes[i*2]=c>>8;bytes[i*2+1]=c&255;});const encoded=figma.base64Encode(bytes);return {length:encoded.length,raw:raw.length,chunk:encoded.slice(OFFSET,OFFSET+14000)};
