#!/usr/bin/env python3
"""Generate typed Swift token names from the checked-in, original Figma variables."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
data = json.loads((ROOT / 'Sources/VibeStatistics/Resources/Nico/foundations.json').read_text())
lines = ['// Generated by scripts/nico/generate-tokens.py. Original values remain in foundations.json.', 'import SwiftUI', '']
for kind, name in [('COLOR', 'NicoColorToken'), ('FLOAT', 'NicoMetricToken'), ('STRING', 'NicoStringToken')]:
    lines.append(f'enum {name}: String, CaseIterable {{')
    for variable in data['variables']:
        if variable['resolvedType'] != kind:
            continue
        raw = variable['name'].split('/')[-1]
        parts = raw.lstrip('-').split('-')
        case = parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])
        lines.append(f'    case {case} = "{raw}"')
    lines.extend(['}', ''])
lines.extend(['extension Nico {', '    static func color(_ token: NicoColorToken) -> Color { color(token.rawValue) }', '    static func number(_ token: NicoMetricToken, mode: Mode = Mode()) -> CGFloat { number(token.rawValue, mode: mode) }', '    static func string(_ token: NicoStringToken, mode: Mode = Mode()) -> String { value(token.rawValue, mode: mode) as! String }', '}', ''])
(ROOT / 'Sources/VibeStatistics/DesignSystem/NicoTokenNames.swift').write_text('\n'.join(lines))
